# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - goarch:
      - amd64
      - arm64
    goos:
      - linux
    main: ./cmd/myhome-presence

dockers:
  - build_flag_templates:
      - "--build-arg=BINARY=myhome-presence"
      - "--build-arg=BUILD_DIR=/"
      - "--platform=linux/amd64"
    dockerfile: deployment/Dockerfile
    extra_files:
      - deployment/config.yaml
    goarch: amd64
    ids:
      - myhome-presence
    image_templates:
      - "quay.io/touchardv/myhome-presence:v{{ .Version }}-amd64"
    use: buildx

  - build_flag_templates:
      - "--build-arg=BINARY=myhome-presence"
      - "--build-arg=BUILD_DIR=/"
      - "--platform=linux/arm64"
    dockerfile: deployment/Dockerfile
    extra_files:
      - deployment/config.yaml
    goarch: arm64
    ids:
      - myhome-presence
    image_templates:
      - "quay.io/touchardv/myhome-presence:v{{ .Version }}-arm64"
    use: buildx

docker_manifests:
  - image_templates:
      - "quay.io/touchardv/myhome-presence:v{{ .Version }}-amd64"
      - "quay.io/touchardv/myhome-presence:v{{ .Version }}-arm64"
    name_template: "quay.io/touchardv/myhome-presence:v{{ .Version }}"
