name: build-main-branch
run-name: Build the project main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Build for linux/amd64
        run: make build GOOS=linux GOARCH=amd64

      - name: Build for linux/arm64
        run: make build GOOS=linux GOARCH=arm64

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            ALPINE_VERSION=3.19
          context: .
          file: deployment/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/touchardv/myhome-presence:latest
